<script setup lang="ts">
// This file was auto-generated by smilelab
// While you can customize this file, you should be sure the following
//   remain present:
//   - <SmileLayout />
//   - <NuxtLayout />
//   - <NuxtPage />
// This will ensure that both `Smile` and `Nuxt` work as-intended.
import { NuxtLayout, NuxtPage, NuxtRouteAnnouncer, SmileLayout } from "#components"
</script>

<template>
  <SmileLayout>
    <NuxtLayout>
      <NuxtRouteAnnouncer />
      <NuxtPage />
    </NuxtLayout>
  </SmileLayout>
</template>
